[package]
name = "clout"
version = "0.0.1"
authors = ["Stephen Lee <sphen.lee@gmail.com>"]
edition = "2018"

description = "commandline output library - holding package"
license = "MIT"

[dependencies]
atty = "^0.2"
termcolor = "^1.0"
lazy_static = "^1.3"
