[package]
name = "clout"
version = "0.1.0"
authors = ["Stephen Lee <sphen.lee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "^0.2"
termcolor = "^1.0"
